language: python
branches:
  only:
  - master
install:
- pip install ghp-import
script:
- make github
env:
  global:
  - secure: ae9yhrae4XZIsBHRFGLUaRowFKYP9nQSbiSyu/ueXLOEIqMyDvuz7gwuOPaikOYKyOWJ6N9rQ6keWFNlCzuCop9OP2RBG3nEnHuD1oPoHig9w00hzKB9ME1RTI+moPQZBnLxR0e5Xb3D0lGsf3RKhaJI9RrkGxcxuJYx50m8t4w=
  - secure: K7NYoAzIvEmGhe/tLF5U6wlVpHIh/Sx81QGefHuwMG/Vs3XAwaOq68PS+bzWckZXa5YmhFmOYnMGSvj3N5d3rp2Bxpem/VMcbzA5A0CNOoZg+NVKVxKJ30Aqq+cXQfEcyg1XF65JO5xWN0v+rdqj+fRcY/qgp4cS/1MHHVEuQt0poDQJ/M2PXn+4axxd1DE509C8Zap2FzTQFA4yqZDkHcIFl0x9h5ZmjKpiG+KKt8RrjEtH+FVK19sRnV9kJ20d7/BlHG+Uhrebxxci6LBbuwoEQnk9/lTpwhJA0DE4PzDrv9rIL9FWI9GYJvfLUF9nQJbw2cdB3vRGfxyNdZmOOb5Q97BqyPB3vupsPImeMrUanOj9cyzIZUZSt/bJx/csHpNwDGuhsJVILhDvnKgGdgfIqcuwlUltOqQcL0wxhYatPxSUq7bVMoIB9U4F/91GbgYaf7lwgvSjCR53Te29RXZI6FC+fE0M/cR2KWJ9lgqePZeR9MW5osm2O+IKSyTetTWVPeolxcaOAd0TxMkT3PWhande446ktkqKCbCpv3Tw3y1vgMo0BRBS7rW2NrQ2XNgt9YSPyIzMr95yqEqxASpvaOclzlmRAY0zc20HxSk/D7+S+Ma2jGjzPLA+fCdninREunpecCJF+lw5kPduIH1CheDQGUSOevUuC694ibs=
